version: "3.9"
services:
  script-server:
    image: alcapone1933/script-server:latest
    container_name: script-server
    restart: always
    ports:
      - 5000:5000
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./app/conf.json:/app/conf/conf.json
      # - ./app/admin-conf.json:/app/conf/conf.json
      # - ./app/runners/:/app/conf/runners
      # - ./app/scripts/:/app/conf/scripts
      # - ./app/logs/:/app/conf/scripts
